### ISSUE TITLE
눈물

### ISSUE THREAD

**Issue by KaniKim** [DeepSE/gpt_playground#31]
우리의 눈물은 흐르지만 웃고있어.
너는

**Comment by ironmansung** [comment]
우리의 눈물은 흐르지만 웃고있어.
너는  ̋나를 사랑해 ̋
너를 만나고 싶어
너의 얼굴을 보고 싶어
너의 눈을 보고 싶어
너의 입을 보고 싶어
너의 마음을 보고 싶어
너의 모습을 기억하고 싶어
내가 있어 좋아해
내가 있어 좋아해
내가 있어 좋아해
너의 모습을 기억하고 싶어
너의 얼굴을 보고 싶어
너의 눈을 보고 싶어
너의 입을 보고 싶어
너의 마음을 보고 싶어
너의 모습을 기억하고 싶어
내가 있어 좋아해
내가 있어 좋아해
(너를) 너를 만나고 싶어
너의 얼굴을 보고 싶어
너의 눈을 보고 싶어
너의 입을 보고 싶어
너의 마음을 보고 싶어
너의 모습을 기억하고 싶어
내가 있어 좋아해
내가 있어 좋아해
내가 있어 좋아해
내가 있어 좋아해
너의 모습을 기억하고 싶어
너의 얼굴을 보고 싶어
너
