### ISSUE TITLE
웃음

### ISSUE THREAD

**Issue by KaniKim** [DeepSE/gpt_playground#32]
웃음끼를 띈 크림빵, 그것을 먹는 너.
그리고 나는

**Comment by ironmansung** [comment]
웃음끼를 띈 크림빵, 그것을 먹는 너.
그리고 나는 너의 것이라는 가사에 따라, 마치 서로가 상대방의 것을 먹는 그런 모습이 그려졌다.
'너의 것'은 '나만의 것'이라는 의미를 지니고 있다.
이는 상대방을 내 소유물처럼 느끼게 된다는 건데,
이 노래를 듣는 모든 사람이 공감할 것 같다.
난 이 가사가 너무 좋아서, 다른 노래들도 찾아 들었다.
'너의 것', '넌 나의 것', '나만의 것'
모두 나만의 것이라는 뜻과 나에게만 보이는 너라는 뜻을 지니고 있다.
모두에게 좋은 노래지만, 조금 다르게 생각하는 사람들은 다를 수도 있을 것 같다.
다른 사람의 것을 먹는 것에 대해서는
조금 생각이 다를 수도 있을 것 같다.
나만의 것이라는 노래의 가사를 읽으니
다른 사람의 것을 먹는 것에 대해 생각해보게 되었다.
너의 것은 나만의 것! 나만의 것을 먹는 것과 다른 사람의 것을 먹는 것은
