### ISSUE TITLE
오늘의 미국 증시

### ISSUE THREAD

**Issue by JuHyung-Son** [DeepSE/gpt_playground#54]
<미국 증시>
나스닥 지수를 제외한 뉴욕 증시는 코로나 재충격의 영향으로 일제히 하락 마감했다.

**Comment by ironmansung** [comment]
<미국 증시>
나스닥 지수를 제외한 뉴욕 증시는 코로나 재충격의 영향으로 일제히 하락 마감했다. 다우지수는 +0.66%, S&P500 지수는 +0.61%, 나스닥은 +1.01% 하락으로 마감했다. ​ ​ ​ <미국채 금리> 유럽증시는 일제히 하락했다. 코로나 확산이 지속되며 경제회복이 둔화될 것이라는 우려와 기술주 약세, 그리고 미국 국채금리의 상승으로 금리가 상승한 것이 금리를 밀어 올리고 있다. 미국의 10년국채 금리는 1.55%까지 상승하며 연중최고치를 기록했고, 30년물은 1.69%까지 상승하며 2년내 최고치를 기록했다. ​ 미 연준이 장기간 저금리를 유지하겠다는 의지를 밝히고 있고, 미국의 경기 회복속도가 예상보다 빠르다는 점 때문에 금리 상승은 제한적일 수 있다는 생각이다. ​ 현재 시장에서는 금리 상승은 계속 이슈가 되고 있다. ​
트럼프는 오늘 기자회견에서 연준의 공격적인 금리 인하가 필요하다고 밝혔다. "연준은 우리가 그렇게 하는 것을 보고 있습니까
