### ISSUE TITLE
각개전투

### ISSUE THREAD

**Issue by developer0hye** [DeepSE/gpt_playground#62]
각개전투 훈련은 훈련소에서 가장 힘든 훈련인데 왜 가장 힘드냐면

**Comment by ironmansung** [comment]
각개전투 훈련은 훈련소에서 가장 힘든 훈련인데 왜 가장 힘드냐면, 훈련중에 가장 피곤하고 힘든 훈련이고, 가장 위험하고 어려운 훈련이기 때문입니다. 각개전투 훈련은 위험성이 가장 높은 훈련이고, 각개전투 훈련은 가장 힘들게 훈련하는 것이라는 인식이 많습니다. 각개전투가 힘들다는 개념은 예전부터 많았지만, 왜 각개전투훈련이 힘들게 느껴지는지, 각개전투가 어떤 것인지에 대해 이해하기 쉽게 설명하고, 각개전투가 왜 가장 힘들고 위험한지에 대해서는 아래 글을 참고하시기 바랍니다. 2010/06/03 - [군대이야기] - 위험하고 힘들다는 각개전투의 진실 2012/12/08 - [군대이야기] - 각개전투는 살인훈련? 각개전투의 진실은? 이 글을 쓰면서 개인적으로 느낀 것은, 이 글을 쓰는 저도 각개전투를 해보지 않았지만, 각개전투의 현실을 누구보다 잘 알고 있다는 것이고, 각개전투의 위험성을 잘 알고 있다는 것입니다. 저는 대한민국 육군 예비역 병장으로 현재도 군 복무중입니다. 대한민국 육군에서
