### ISSUE TITLE
호날두보다 메시가 축구를 더 

### ISSUE THREAD

**Issue by developer0hye** [DeepSE/gpt_playground#79]
호날두보다 메시가 축구를 더

**Comment by ironmansung** [comment]
호날두보다 메시가 축구를 더  잘하고,  메시가  호날두보다  축구를  더  잘한다는  것을  사람들이  알게  되면  축구는  재미없는  것이 되고 말 것이다.
이는 비단 스포츠의 영역에만 해당하는 것이 아니라, 우리 일상생활에서도 충분히 적용될 수 있다.
스포츠에서도 '승리하는 것'과 '성공하는 것'이 일치하지 않는 경기는 승자와 패자만 있을 뿐, '스포츠'라는 말이 무색해진다. 이 때문에 승자와 패자가 없는 스포츠, 승자와 패자가 모두 즐길 수 있는 스포츠를 지향하는 사람들이 늘고 있다. 이들은 승자와 패자를 가리지 않고 모두가 같이 즐길 수 있는 스포츠를 위해서는 경기를 보는 동안에는 승부의 결과가 어떠하던 신경 쓰지 않고 경기 그 자체에 몰입할 수 있어야 하며, 이를 위해서는 경기를 관람하는 사람들이 경기에 몰두할 수 있도록 경기를 볼 수 있는 시설과, 그 시설을 설계하고 운영할 수 있는 사람들이 필요하다는 것을 강조한다.(
