### ISSUE TITLE
메시보다 호날두가 축구를 더

### ISSUE THREAD

**Issue by developer0hye** [DeepSE/gpt_playground#80]
메시보다 호날두가 축구를 더

**Comment by ironmansung** [comment]
메시보다 호날두가 축구를 더 잘한다? 호날두는 세계 최고의 축구선수다. 그러나 메시는 그보다 더 뛰어난 선수이다. - 호나우두 - 메시와 호날두는 차원이 다른 선수라고 생각합니다. 호날두가 실력이 있는 선수가 아니라는게 아니라, 여기는 호날두 게시판입니다. 호날두가 더 뛰어나다는 걸 말하고 싶을 뿐입니다. - 방금전까지 호날두가 세계 최고의 선수라고 생각했는데, 메시는 비교할 수도 없는 선수라는 것을 알았습니다. - 내생각에 동의한다. - 메시가 호날두보다 더 뛰어나다. - 바르샤팬들이 화날만도 하다. - 내생각엔 이번 경기에서 메시의 모습은 그 이상이였다. - 메시는 세계 최고의 축구선수다. - 메시는 호날두보다 더 뛰어나다. - 메시가 세계최고라는 호날두를 꺾었다. - 우리는 호날두 없이도 잘 할 수 있지만, 호날두는 분명히 세계 최고다. 호날두가 없어도 우린 잘 할 수 있다. 우린 호날두가 필요하다. 호날두는 대단하다. 나는 내가 호날두와 같이 뛰고 있다고 느낀다. - 메시가 세계최고다. - 호날두가 메시를 밀어냈다. -
